### ISSUE TITLE
Failed to connect to xsounds.org port 80

### ISSUE THREAD

**Issue by lvicentesanchez** [archhaskell/archlinux#18]
I'm getting this error while trying to update some packages using pacaur:

```
error: failed retrieving file 'haskell-core.db' from xsounds.org : Failed to connect to xsounds.org port 80: Connection refused
```

**Comment by lvicentesanchez** [comment]
@magthe I still can't connect.

**Comment by magthe** [comment]
Read this: https://mail.haskell.org/pipermail/arch-haskell/2017-October/004994.html
